### ISSUE TITLE
Altering the extension

### ISSUE THREAD

**Issue by rickthomasjr** [justinweiss/reactive_resource#2]
One of my biggest gripes with ActiveResource is the inability to change the file extension of calls, particularly on custom method calls (AFAIK, the custom_method_url can't be overridden).  Does this gem resolve that problem?

**Comment by justinweiss** [comment]
Are you trying to change the extension on a per-api basis, a per-resource basis, or a per-action basis? The first one is easy, the second one should be possible, and the third one would probably be a little tricky.

**Comment by rickthomasjr** [comment]
I am trying to change it on a per-API basis.
On Mar 10, 2011 12:05 PM, "justinweiss" <
reply@reply.github.com>
wrote:

> Are you trying to change the extension on a per-api basis, a per-resource
> basis, or a per-action basis? The first one is easy, the second one should
> be possible, and the third one would probably be a little tricky.
> 
> https://github.com/justinweiss/reactive_resource/issues/2#comment_856664

**Comment by justinweiss** [comment]
I think you should be able to handle that with ActiveResource using a custom format. Twilio, for instance, doesn't use extensions on their REST API so I had to do something similar: https://github.com/justinweiss/twilio_resource/blob/master/lib/twilio_resource/twilio_format.rb

Once you create a format, you can set it using something like 
    self.format = :twilio
inside your resource class. ActiveResource has a bug where not having an extension doesn't work (which ReactiveResource fixes), but other than that, you should be able to handle it with vanilla ActiveResource. You can still use ReactiveResource for the other features though :-) Does that help?

**Comment by rickthomasjr** [comment]
That is awesome stuff.  Thanks.

**Comment by rickthomasjr** [comment]
My employer's blog is ranked pretty well in Google - do you mind if I make a
blog entry about this topic?  I haven't seen this solution anywhere, so an
entry could help a lot of folks.

**Comment by justinweiss** [comment]
Yeah, definitely! It took some digging through the ActiveResource documentation and code to figure it out in the first place, so it would be nice to have it written down somewhere.

**Comment by rickthomasjr** [comment]
This should be out later this week.  I'm linking to your reactive_resource
github - is there another place you'd prefer I link to you as a reference?

Also, I have run into one more problem.  I've slept since I fixed this
problem in Active Resource, but my objects are being dasherized again now
that I'm inheriting ReactiveResource.  Are you aware of any way to prevent
that from happening?  (Dasherizing converts underscores to dashes in field
names).

Thanks for all your assistance.

Rick Thomas

**Comment by justinweiss** [comment]
Cool! Linking to the github repo should be fine, I don't think I have any other place where I talk about the gem. As far as the dasherizing, I'm not totally sure -- I don't think ReactiveResource modifies that at all. You might be able to override the encode/decode functions in your custom format to un-dasherize or otherwise massage the data you're sending to or from the API.
